#!/usr/bin/env python3
"""Generate data/marker_names_cs.js from marker-name translation fragments.

The fragments are small text files containing lines like:
    "English marker name": "Český název",
Comments (#) and blank lines are ignored.

The script validates that every unique marker name from the JSON data files
has a translation and reports keys that exist in the fragments but not in the
data (so typos are caught). It then writes data/marker_names_cs.js exposing
window.MARKER_NAME_CS.
"""

import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DATA = ROOT / "data"
FRAGMENT_DIR = Path(sys.argv[1]) if len(sys.argv) > 1 else Path(
    r"C:\Users\user\AppData\Local\Temp\opencode"
)
OUT = DATA / "marker_names_cs.js"

LINE_RE = re.compile(r'^\s*"((?:[^"\\]|\\.)*)":\s*"((?:[^"\\]|\\.)*)",?\s*$')


def unescape(s):
    return s.replace('\\"', '"').replace("\\\\", "\\")


def parse_fragments(frag_dir):
    translations = {}
    for path in sorted(frag_dir.glob("frag*.txt")):
        for lineno, raw in enumerate(path.read_text(encoding="utf-8").splitlines(), 1):
            line = raw.strip()
            if not line or line.startswith("#"):
                continue
            m = LINE_RE.match(line)
            if not m:
                print(f"WARNING: could not parse {path.name}:{lineno}: {raw!r}")
                continue
            key = unescape(m.group(1))
            value = unescape(m.group(2))
            if key in translations:
                raise SystemExit(
                    f"DUPLICATE key {key!r} at {path.name}:{lineno}; "
                    f"already defined in {translations[key][0]}"
                )
            translations[key] = (value, f"{path.name}:{lineno}")
    return translations


def collect_names():
    names = set()
    for fname in ("markers_trosky.json", "markers_kuttenberg.json"):
        data = json.loads((DATA / fname).read_text(encoding="utf-8"))
        for marker in data["markers"]:
            names.add(marker["name"])
    return names


def js_escape(s):
    return s.replace("\\", "\\\\").replace('"', '\\"').replace("\n", "\\n")


def main():
    translations = parse_fragments(FRAGMENT_DIR)
    print(f"translated pairs: {len(translations)}")

    names = collect_names()
    print(f"unique marker names in data: {len(names)}")

    missing = sorted(n for n in names if n not in translations)
    unused = sorted(n for n in translations if n not in names)
    dupes = [n for n in names if n in translations and False]

    if missing:
        print(f"\nMISSING ({len(missing)}) translations:")
        for n in missing:
            print("  " + n)
    if unused:
        print(f"\nUNUSED ({len(unused)}) keys in fragments (not in data):")
        for n in unused:
            print("  " + n)

    if missing:
        raise SystemExit(
            f"\n{len(missing)} marker names have no translation yet. "
            f"Add them to a fragment and rerun."
        )

    lines = []
    lines.append("// Czech translations for map marker names.")
    lines.append("// Generated by tools/gen_marker_names_cs.py - do not edit by hand.")
    lines.append("(function () {")
    lines.append("  window.MARKER_NAME_CS = {")
    for key in sorted(translations):
        value = translations[key][0]
        lines.append(f'    "{js_escape(key)}": "{js_escape(value)}",')
    lines.append("  };")
    lines.append("})();")
    lines.append("")

    OUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"\nwrote {OUT} ({len(translations)} entries)")


if __name__ == "__main__":
    main()